bool engine_running                   # 0 - off; 1 - the engine is running
float64 engine_rotation_speed_rpm     # The value of the rotational speed of the combustion engine
float64 engine_coolant_temp_celsius   # 0 - 100 - value determining the temperature ( o C )
float64 engine_fuel_level_percent     # Value specifying % of tank filling
float64 engine_oil_pressure_bar       # 0-100 (100 means 10 bar)

