float64 left_front_wheel_encoder_imp    #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_front_wheel_encoder_imp   #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 left_rear_wheel_encoder_imp     #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_rear_wheel_encoder_imp    #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses

float64 left_front_wheel_rotational_speed_rpm   #ID32: rotational speed( rpm );
float64 right_front_wheel_rotational_speed_rpm   
float64 left_rear_wheel_rotational_speed_rpm     
float64 right_rear_wheel_rotational_speed_rpm    

float64 left_front_wheel_turn_angle_rad    #ID32: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_front_wheel_turn_angle_rad   #ID32: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 left_rear_wheel_turn_angle_rad     #ID32: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_rear_wheel_turn_angle_rad    #ID32: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
#left -90 degrees; max turn right 90 degrees

float64 wheels_average_rotational_speed_rpm  #ID34: 